
services:
  nginx:
    container_name: nginx

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - wp-nginx

    build:
      context: requirements/nginx

    depends_on:
      - mariadb

    ports:
      - "443:443"

    restart:
      on-failure
    
    env_file:
      - .env

  mariadb:
    container_name: mariadb

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - mariadb-wp
    build:
      context: requirements/mariadb

    expose:
      - "3306"

    restart:
      on-failure

    env_file:
      - .env
      
  wordpress:
    container_name: wordpress

    volumes:
      - wordpress_data:/var/www/html

    build:
      context: requirements/wordpress

    depends_on:
      - mariadb

    networks:
      - wp-nginx
      - mariadb-wp

    expose:
      - "9000"

    restart: 
      on-failure

    env_file:
      - .env

networks:
  wp-nginx:
    driver: bridge
  mariadb-wp:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local