
services:
  nginx:
    container_name: nginx

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - inception

    build:
      context: requirements/nginx

    depends_on:
      - mariadb

    ports:
      - "443:443"
    restart:
      on-failure
    
    env_file:
      - .env

  mariadb:
    container_name: mariadb

    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - inception
    build:
      context: requirements/mariadb

    expose:
      - "3306"
    restart:
      on-failure

    env_file:
      - .env
      
  wordpress:
    container_name: wordpress

    volumes:
      - wordpress_data:/var/www/html

    build:
      context: requirements/wordpress  # Path to the WordPress Dockerfile

    depends_on:
      - mariadb

    networks:
      - inception

    expose:
      - "9000"

    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${SQL_DATABASE}
      WORDPRESS_DB_USER: ${SQL_USER}
      WORDPRESS_DB_PASSWORD: ${SQL_PASSWORD}

    restart: 
      on-failure

    env_file:
      - .env

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local